/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2026-03-16 15:42:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Search Results</title>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: sans-serif; padding: 16px; }\n");
      out.write("        table { border-collapse: collapse; width: 100%; margin-top: 12px; }\n");
      out.write("        th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }\n");
      out.write("        th { background-color: #f2f2f2; }\n");
      out.write("        tr:nth-child(even) { background-color: #fafafa; }\n");
      out.write("        .search-section { margin-bottom: 24px; padding: 12px; border: 1px solid #ddd; border-radius: 4px; }\n");
      out.write("        .search-section h3 { margin-top: 0; }\n");
      out.write("        select, input[type=text] { padding: 6px; font-size: 14px; }\n");
      out.write("        button { padding: 6px 14px; font-size: 14px; cursor: pointer; }\n");
      out.write("        .divider { text-align: center; color: #999; margin: 12px 0; font-style: italic; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <a href=\"/\">Home</a> | <a href=\"/patients\">All Patients</a> | <a href=\"/stats\">Statistics</a> | <a href=\"/export\">Download JSON</a>\n");
      out.write("    <h1>Search</h1>\n");
      out.write("\n");
      out.write("    ");

        String[] cols = (String[]) request.getAttribute("columnNames");
        String distinctValuesJson = (String) request.getAttribute("distinctValuesJson");
        String selectedCol = (String) request.getAttribute("selectedCol");
        String selectedVal = (String) request.getAttribute("selectedVal");
        String query = (String) request.getAttribute("query");
        if (selectedCol == null) selectedCol = "";
        if (selectedVal == null) selectedVal = "";
        if (query == null) query = "";
    
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Column + Value search -->\n");
      out.write("    <div class=\"search-section\">\n");
      out.write("        <h3>Filter by Column</h3>\n");
      out.write("        <form action=\"/search\" method=\"get\" id=\"colForm\">\n");
      out.write("            <select name=\"col\" id=\"colSelect\">\n");
      out.write("                <option value=\"\">-- Select column --</option>\n");
      out.write("                ");
 for (String c : cols) { 
      out.write("\n");
      out.write("                    <option value=\"");
      out.print( c );
      out.write('"');
      out.write(' ');
      out.print( c.equals(selectedCol) ? "selected" : "" );
      out.write('>');
      out.print( c );
      out.write("</option>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </select>\n");
      out.write("            &nbsp;\n");
      out.write("            <select name=\"val\" id=\"valSelect\">\n");
      out.write("                <option value=\"\">-- Select value --</option>\n");
      out.write("            </select>\n");
      out.write("            &nbsp;\n");
      out.write("            <button type=\"submit\">Filter</button>\n");
      out.write("            ");
 if (!selectedCol.isEmpty()) { 
      out.write("\n");
      out.write("                &nbsp;<a href=\"/search\">Clear</a>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"divider\">— or —</div>\n");
      out.write("\n");
      out.write("    <!-- Free-text search -->\n");
      out.write("    <div class=\"search-section\">\n");
      out.write("        <h3>Full-text Search</h3>\n");
      out.write("        <form action=\"/search\" method=\"get\">\n");
      out.write("            <input type=\"text\" name=\"q\" value=\"");
      out.print( query );
      out.write("\" size=\"40\" placeholder=\"Search across all fields...\" />\n");
      out.write("            <button type=\"submit\">Search</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Results -->\n");
      out.write("    ");

        ArrayList<String[]> results = (ArrayList<String[]>) request.getAttribute("results");
        String searchMode = (String) request.getAttribute("searchMode");
        boolean hasSearch = ("column".equals(searchMode) && !selectedCol.isEmpty())
                         || ("text".equals(searchMode) && !query.isEmpty());
    
      out.write("\n");
      out.write("    ");
 if (hasSearch) { 
      out.write("\n");
      out.write("        <p><strong>");
      out.print( results.size() );
      out.write("</strong> result(s)\n");
      out.write("        ");
 if ("column".equals(searchMode)) { 
      out.write("\n");
      out.write("            where <strong>");
      out.print( selectedCol );
      out.write("</strong> = \"<strong>");
      out.print( selectedVal );
      out.write("</strong>\"\n");
      out.write("        ");
 } else { 
      out.write("\n");
      out.write("            for \"<strong>");
      out.print( query );
      out.write("</strong>\"\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        </p>\n");
      out.write("        ");
 if (!results.isEmpty()) { 
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("                ");
 for (String c : cols) { 
      out.write("<th>");
      out.print( c );
      out.write("</th>");
 } 
      out.write("\n");
      out.write("            </tr>\n");
      out.write("            ");
 for (String[] patient : results) { 
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    ");
 for (String value : patient) { 
      out.write("\n");
      out.write("                        <td>");
      out.print( value != null ? value : "" );
      out.write("</td>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </table>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        var distinctValues = ");
      out.print( distinctValuesJson );
      out.write(";\n");
      out.write("        var colSelect = document.getElementById(\"colSelect\");\n");
      out.write("        var valSelect = document.getElementById(\"valSelect\");\n");
      out.write("        var preselectedVal = \"");
      out.print( selectedVal.replace("\"", "\\\"") );
      out.write("\";\n");
      out.write("\n");
      out.write("        function populateValues(col) {\n");
      out.write("            valSelect.innerHTML = \"<option value=''>-- Select value --</option>\";\n");
      out.write("            if (!col || !distinctValues[col]) return;\n");
      out.write("            var values = distinctValues[col];\n");
      out.write("            for (var i = 0; i < values.length; i++) {\n");
      out.write("                var opt = document.createElement(\"option\");\n");
      out.write("                opt.value = values[i];\n");
      out.write("                opt.text = values[i] === \"\" ? \"(empty)\" : values[i];\n");
      out.write("                if (values[i] === preselectedVal) opt.selected = true;\n");
      out.write("                valSelect.appendChild(opt);\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        // Populate on page load if a column is already selected\n");
      out.write("        populateValues(colSelect.value);\n");
      out.write("\n");
      out.write("        colSelect.addEventListener(\"change\", function () {\n");
      out.write("            preselectedVal = \"\";\n");
      out.write("            populateValues(this.value);\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
