/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2026-03-16 15:41:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;
import java.util.ArrayList;

public final class stats_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


    private String jsLabels(Map<String, Long> map) {
        StringBuilder sb = new StringBuilder("[");
        boolean first = true;
        for (String k : map.keySet()) {
            if (!first) sb.append(",");
            sb.append("\"").append(k.replace("\\","\\\\").replace("\"","\\\"")).append("\"");
            first = false;
        }
        return sb.append("]").toString();
    }

    private String jsData(Map<String, Long> map) {
        StringBuilder sb = new StringBuilder("[");
        boolean first = true;
        for (Long v : map.values()) {
            if (!first) sb.append(",");
            sb.append(v);
            first = false;
        }
        return sb.append("]").toString();
    }

    private Map<String, Long> topN(Map<String, Long> map, int n) {
        Map<String, Long> result = new java.util.LinkedHashMap<>();
        int count = 0;
        for (Map.Entry<String, Long> e : map.entrySet()) {
            if (count++ >= n) break;
            result.put(e.getKey(), e.getValue());
        }
        return result;
    }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Patient Statistics</title>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        body { font-family: sans-serif; padding: 16px; }\n");
      out.write("        h2 { margin-top: 36px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }\n");
      out.write("        h3 { margin-top: 0; color: #444; }\n");
      out.write("        table { border-collapse: collapse; margin-bottom: 24px; }\n");
      out.write("        th, td { border: 1px solid #ccc; padding: 8px 12px; text-align: left; }\n");
      out.write("        th { background-color: #f2f2f2; }\n");
      out.write("        .chart-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin-bottom: 40px; }\n");
      out.write("        .chart-box { background: #fafafa; border: 1px solid #e0e0e0; border-radius: 6px; padding: 16px; }\n");
      out.write("        .chart-wide { grid-column: 1 / -1; }\n");
      out.write("        canvas { max-height: 300px; }\n");
      out.write("        .summary-bar { display: flex; gap: 32px; margin-bottom: 32px; flex-wrap: wrap; }\n");
      out.write("        .summary-card { background: #f0f4ff; border: 1px solid #c5d0f0; border-radius: 6px; padding: 16px 24px; }\n");
      out.write("        .summary-card .value { font-size: 2em; font-weight: bold; color: #2a4ab0; }\n");
      out.write("        .summary-card .label { color: #555; font-size: 0.9em; margin-top: 4px; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <a href=\"/\">Home</a> | <a href=\"/patients\">All Patients</a> | <a href=\"/search\">Search</a> | <a href=\"/export\">Download JSON</a>\n");
      out.write("    <h1>Patient Statistics</h1>\n");
      out.write("\n");
      out.write("    ");

        String[] cols = (String[]) request.getAttribute("columnNames");
        double avgAge = (Double) request.getAttribute("averageAge");
        Map<String, Long> avd = (Map<String, Long>) request.getAttribute("aliveVsDeceased");
        Map<String, Long> byGender = (Map<String, Long>) request.getAttribute("byGender");
        Map<String, Long> byMarital = (Map<String, Long>) request.getAttribute("byMarital");
        Map<String, Long> byRace = (Map<String, Long>) request.getAttribute("byRace");
        Map<String, Long> byState = (Map<String, Long>) request.getAttribute("byState");
        Map<String, Long> byCity = (Map<String, Long>) request.getAttribute("byCity");
        Map<String, Long> ageDist = (Map<String, Long>) request.getAttribute("ageDistribution");
        long totalPatients = 0;
        for (Long v : avd.values()) totalPatients += v;
        long aliveCount = avd.getOrDefault("Alive", 0L);
    
      out.write("\n");
      out.write("\n");
      out.write("    <!-- Summary cards -->\n");
      out.write("    <div class=\"summary-bar\">\n");
      out.write("        <div class=\"summary-card\">\n");
      out.write("            <div class=\"value\">");
      out.print( totalPatients );
      out.write("</div>\n");
      out.write("            <div class=\"label\">Total Patients</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"summary-card\">\n");
      out.write("            <div class=\"value\">");
      out.print( aliveCount );
      out.write("</div>\n");
      out.write("            <div class=\"label\">Living Patients</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"summary-card\">\n");
      out.write("            <div class=\"value\">");
      out.print( String.format("%.1f", avgAge) );
      out.write("</div>\n");
      out.write("            <div class=\"label\">Average Age (living)</div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Charts -->\n");
      out.write("    <h2>Charts</h2>\n");
      out.write("    <div class=\"chart-grid\">\n");
      out.write("\n");
      out.write("        <div class=\"chart-box chart-wide\">\n");
      out.write("            <h3>Age Distribution (Living Patients)</h3>\n");
      out.write("            <canvas id=\"chartAge\"></canvas>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"chart-box\">\n");
      out.write("            <h3>Alive vs Deceased</h3>\n");
      out.write("            <canvas id=\"chartAlive\"></canvas>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"chart-box\">\n");
      out.write("            <h3>Gender Distribution</h3>\n");
      out.write("            <canvas id=\"chartGender\"></canvas>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"chart-box\">\n");
      out.write("            <h3>Race Distribution</h3>\n");
      out.write("            <canvas id=\"chartRace\"></canvas>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"chart-box\">\n");
      out.write("            <h3>Top 10 Cities</h3>\n");
      out.write("            <canvas id=\"chartCity\"></canvas>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        const COLORS = [\n");
      out.write("            \"#4e79a7\",\"#f28e2b\",\"#e15759\",\"#76b7b2\",\"#59a14f\",\n");
      out.write("            \"#edc948\",\"#b07aa1\",\"#ff9da7\",\"#9c755f\",\"#bab0ac\"\n");
      out.write("        ];\n");
      out.write("\n");
      out.write("        new Chart(document.getElementById(\"chartAge\"), {\n");
      out.write("            type: \"bar\",\n");
      out.write("            data: {\n");
      out.write("                labels: ");
      out.print( jsLabels(ageDist) );
      out.write(",\n");
      out.write("                datasets: [{ label: \"Patients\", data: ");
      out.print( jsData(ageDist) );
      out.write(",\n");
      out.write("                    backgroundColor: \"#4e79a7\", borderRadius: 4 }]\n");
      out.write("            },\n");
      out.write("            options: { plugins: { legend: { display: false } },\n");
      out.write("                       scales: { y: { beginAtZero: true, ticks: { stepSize: 1 } } } }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        new Chart(document.getElementById(\"chartAlive\"), {\n");
      out.write("            type: \"doughnut\",\n");
      out.write("            data: {\n");
      out.write("                labels: ");
      out.print( jsLabels(avd) );
      out.write(",\n");
      out.write("                datasets: [{ data: ");
      out.print( jsData(avd) );
      out.write(",\n");
      out.write("                    backgroundColor: [\"#59a14f\",\"#e15759\"] }]\n");
      out.write("            },\n");
      out.write("            options: { plugins: { legend: { position: \"bottom\" } } }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        new Chart(document.getElementById(\"chartGender\"), {\n");
      out.write("            type: \"doughnut\",\n");
      out.write("            data: {\n");
      out.write("                labels: ");
      out.print( jsLabels(byGender) );
      out.write(",\n");
      out.write("                datasets: [{ data: ");
      out.print( jsData(byGender) );
      out.write(",\n");
      out.write("                    backgroundColor: [\"#4e79a7\",\"#f28e2b\",\"#e15759\"] }]\n");
      out.write("            },\n");
      out.write("            options: { plugins: { legend: { position: \"bottom\" } } }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        new Chart(document.getElementById(\"chartRace\"), {\n");
      out.write("            type: \"bar\",\n");
      out.write("            data: {\n");
      out.write("                labels: ");
      out.print( jsLabels(byRace) );
      out.write(",\n");
      out.write("                datasets: [{ label: \"Patients\", data: ");
      out.print( jsData(byRace) );
      out.write(",\n");
      out.write("                    backgroundColor: COLORS }]\n");
      out.write("            },\n");
      out.write("            options: {\n");
      out.write("                indexAxis: \"y\",\n");
      out.write("                plugins: { legend: { display: false } },\n");
      out.write("                scales: { x: { beginAtZero: true } }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        ");
 Map<String, Long> top10 = topN(byCity, 10); 
      out.write("\n");
      out.write("        new Chart(document.getElementById(\"chartCity\"), {\n");
      out.write("            type: \"bar\",\n");
      out.write("            data: {\n");
      out.write("                labels: ");
      out.print( jsLabels(top10) );
      out.write(",\n");
      out.write("                datasets: [{ label: \"Patients\", data: ");
      out.print( jsData(top10) );
      out.write(",\n");
      out.write("                    backgroundColor: COLORS }]\n");
      out.write("            },\n");
      out.write("            options: {\n");
      out.write("                indexAxis: \"y\",\n");
      out.write("                plugins: { legend: { display: false } },\n");
      out.write("                scales: { x: { beginAtZero: true } }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("    <!-- Data Tables -->\n");
      out.write("    <h2>Oldest &amp; Youngest Living Patient</h2>\n");
      out.write("    <h3>Oldest</h3>\n");
      out.write("    <table>\n");
      out.write("        <tr>");
 for (String c : cols) { 
      out.write("<th>");
      out.print( c );
      out.write("</th>");
 } 
      out.write("</tr>\n");
      out.write("        <tr>");
 for (String v : (String[]) request.getAttribute("oldestPatient")) { 
      out.write("<td>");
      out.print( v != null ? v : "" );
      out.write("</td>");
 } 
      out.write("</tr>\n");
      out.write("    </table>\n");
      out.write("    <h3>Youngest</h3>\n");
      out.write("    <table>\n");
      out.write("        <tr>");
 for (String c : cols) { 
      out.write("<th>");
      out.print( c );
      out.write("</th>");
 } 
      out.write("</tr>\n");
      out.write("        <tr>");
 for (String v : (String[]) request.getAttribute("youngestPatient")) { 
      out.write("<td>");
      out.print( v != null ? v : "" );
      out.write("</td>");
 } 
      out.write("</tr>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <h2>Alive vs Deceased</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr><th>Status</th><th>Count</th></tr>\n");
      out.write("        ");
 for (Map.Entry<String, Long> e : avd.entrySet()) { 
      out.write("\n");
      out.write("        <tr><td>");
      out.print( e.getKey() );
      out.write("</td><td>");
      out.print( e.getValue() );
      out.write("</td></tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <h2>By Gender</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr><th>Gender</th><th>Count</th></tr>\n");
      out.write("        ");
 for (Map.Entry<String, Long> e : byGender.entrySet()) { 
      out.write("\n");
      out.write("        <tr><td>");
      out.print( e.getKey() );
      out.write("</td><td>");
      out.print( e.getValue() );
      out.write("</td></tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <h2>By Marital Status</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr><th>Status</th><th>Count</th></tr>\n");
      out.write("        ");
 for (Map.Entry<String, Long> e : byMarital.entrySet()) { 
      out.write("\n");
      out.write("        <tr><td>");
      out.print( e.getKey() );
      out.write("</td><td>");
      out.print( e.getValue() );
      out.write("</td></tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <h2>By Race</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr><th>Race</th><th>Count</th></tr>\n");
      out.write("        ");
 for (Map.Entry<String, Long> e : byRace.entrySet()) { 
      out.write("\n");
      out.write("        <tr><td>");
      out.print( e.getKey() );
      out.write("</td><td>");
      out.print( e.getValue() );
      out.write("</td></tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <h2>By State</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr><th>State</th><th>Count</th></tr>\n");
      out.write("        ");
 for (Map.Entry<String, Long> e : byState.entrySet()) { 
      out.write("\n");
      out.write("        <tr><td>");
      out.print( e.getKey() );
      out.write("</td><td>");
      out.print( e.getValue() );
      out.write("</td></tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <h2>By City</h2>\n");
      out.write("    <table>\n");
      out.write("        <tr><th>City</th><th>Count</th></tr>\n");
      out.write("        ");
 for (Map.Entry<String, Long> e : byCity.entrySet()) { 
      out.write("\n");
      out.write("        <tr><td>");
      out.print( e.getKey() );
      out.write("</td><td>");
      out.print( e.getValue() );
      out.write("</td></tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
